spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    enabled=true:

server:
  port : 8082
